# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "AIYWLNFNEZoCbwAYlo/8J5NcwffwI9jGkdU7PIcUeiYZl4W4YVcUob9AemJQJHY0B93/TmBIR6vU3qtxxL4LBu3nUb8oI7YW6W2uOh+XSbIQqwVwdroXSHZ/BaiLbFJa5z3JtVX+rqIPD0IEyTgcs2Tgc7nGc3M3BqmLEOcxqs86A90OIiiFOTLZWTKx7yV4AzzkSkIgsU8BcqhWVqsT+t7J8wRFVGfE6BUrJIt24wbbisscYnyTtTCXMXwjBEPIVfY+M+B/tsloKbmdbnTEsnmVDnG/QDTmz9CVTkPIVgAIR9Ibg4SqqFFK4yrnrIG+1r9eU7cesHDpVlakuU+hYXasKbQ4JP3PAGlyqKVKJwQ3G+VX6T+SIFNVHHo9+Miy/b8ar5YtVSgdKA0TCMnwN/+Ug+JMXmbxr+5mXjoyP3Bzi01NQe3MZ6oX3ze3+Hxcbcr0+613mqhcj39JzLge/fdIsFQsig8924X6vZ0/QwV5FS92vVvCrBw3Qa3HMNX+1TlH+VVZc6toObJ3akhIkK7/PRDcqp9NF0z+cYuDuk9tLlC+6TIGr/eTOwqVKHqwouyUBDzCSo9ZRdh1ma7jgpHDSbuD93bQWuAlACqWvRWsd3KXgxfMA0aZl93KQQDAesdajmf7JRpzhrRdP8BJ74LDJAx3zvyaR042/WIsCG4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
